Import('env', 'sys', 'plugins')

plugins += env.SharedLibrary('ao', ['direct/ao.cpp'])
plugins += env.SharedLibrary('direct', ['direct/direct.cpp'])

# tof path (added)
# plugins += env.SharedLibrary('dopplertofpath', ['tofpath/doppler_tof_path.cpp'])
plugins += env.SharedLibrary('fmcwfield', ['fmcw/fmcw_field.cpp'])
plugins += env.SharedLibrary('fmcwpsd', ['fmcw/fmcw_psd.cpp'])
# plugins += env.SharedLibrary('transient', ['transient/transientpath.cpp'])
# plugins += env.SharedLibrary('timegatedpath', ['transient/timegatedpath.cpp'])

# plugins += env.SharedLibrary('eventpath', ['event/eventpath.cpp'])
# plugins += env.SharedLibrary('eventpathcorrelated', ['event/eventpathcorrelated.cpp'])
# plugins += env.SharedLibrary('eventpathcorrelatedsingle', ['event/eventpathcorrelatedsingle.cpp'])
# plugins += env.SharedLibrary('eventpathsmooth', ['event/eventpathsmooth.cpp'])
# plugins += env.SharedLibrary('eventpathexact', ['event/eventpathexact.cpp'])
# plugins += env.SharedLibrary('eventpathcorrelatedrough', ['event/eventpathcorrelatedrough.cpp'])

plugins += env.SharedLibrary('velocity', ['geometry/velocity.cpp'])
plugins += env.SharedLibrary('depth', ['geometry/depth.cpp'])

plugins += env.SharedLibrary('path', ['path/path.cpp'])
plugins += env.SharedLibrary('volpath', ['path/volpath.cpp'])
plugins += env.SharedLibrary('volpath_simple', ['path/volpath_simple.cpp'])
plugins += env.SharedLibrary('ptracer', ['ptracer/ptracer.cpp', 'ptracer/ptracer_proc.cpp'])

# Photon mapping-based techniques
plugins += env.SharedLibrary('photonmapper', ['photonmapper/photonmapper.cpp', 'photonmapper/bre.cpp'])
plugins += env.SharedLibrary('ppm', ['photonmapper/ppm.cpp'])
plugins += env.SharedLibrary('sppm', ['photonmapper/sppm.cpp'])

# Miscellaneous
plugins += env.SharedLibrary('vpl', ['vpl/vpl.cpp'])
plugins += env.SharedLibrary('adaptive', ['misc/adaptive.cpp'])
plugins += env.SharedLibrary('irrcache', ['misc/irrcache.cpp', 'misc/irrcache_proc.cpp'])
plugins += env.SharedLibrary('multichannel', ['misc/multichannel.cpp'])
plugins += env.SharedLibrary('field', ['misc/field.cpp'])
plugins += env.SharedLibrary('motion', ['misc/motion.cpp'])

# Bidirectional techniques
bidirEnv = env.Clone()
bidirEnv.Append(LIBS=['mitsuba-bidir'])
bidirEnv.Append(LIBPATH=['#src/libbidir'])

plugins += bidirEnv.SharedLibrary('bdpt',
        ['bdpt/bdpt.cpp', 'bdpt/bdpt_wr.cpp', 'bdpt/bdpt_proc.cpp'])

plugins += bidirEnv.SharedLibrary('pssmlt',
        ['pssmlt/pssmlt.cpp', 'pssmlt/pssmlt_sampler.cpp',
    'pssmlt/pssmlt_proc.cpp']);

plugins += bidirEnv.SharedLibrary('mlt',
        ['mlt/mlt.cpp', 'mlt/mlt_proc.cpp']
)

plugins += bidirEnv.SharedLibrary('erpt',
        ['erpt/erpt.cpp', 'erpt/erpt_proc.cpp']
)

Export('plugins')
